language: node_js
node_js:
- "node"
script:
- npm test
- CI=false npm run build
env:
- MY_VAR=EverythingIsAwesomen
- NODE_ENV=TEST
deploy:
- provider: pages
- skip-cleanup: true
- github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
- keep-history: true
- on:
    branch: master