language: node_js
node_js:
- "node"
script:
- npm test
- CI=false npm run build
env:
- NODE_ENV=TEST
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    local_dir: build 
    on:
        branch: development